# CassandraCTI - Modular Cyber Threat Intelligence Aggregator
# Copyright (C) 2025 Franck Ferman
# service.py -- generate and install an OS service (systemd or OpenRC) that
# keeps `cassandra run` alive across crashes and reboots.
from __future__ import annotations
import os
import sys
import shutil
import subprocess  # nosec B404 -- fixed argv lists, never shell=True (see _run)
from pathlib import Path
from typing import List, Optional

SYSTEMD_SYSTEM_DIR = Path("/etc/systemd/system")
OPENRC_DIR = Path("/etc/init.d")


# --------------------------------------------------------------------------- #
# Discovery
# --------------------------------------------------------------------------- #
def detect_init() -> str:
    """Return the running init system: 'systemd', 'openrc', or 'unknown'.

    Prefer the runtime signal (`/run/systemd/system` exists only when systemd is
    PID 1) over merely finding the binary, so a box with both installed is
    classified by what is actually managing services.
    """
    if os.path.isdir("/run/systemd/system"):
        return "systemd"
    if shutil.which("rc-service") or os.path.isdir("/run/openrc"):
        return "openrc"
    if shutil.which("systemctl"):
        return "systemd"
    return "unknown"


def resolve_exec() -> str:
    """Absolute path to the installed `cassandra` entry point."""
    exe = shutil.which("cassandra")
    if exe:
        return exe
    # The console script is installed next to the running interpreter.
    cand = Path(sys.executable).with_name("cassandra")
    return str(cand) if cand.exists() else "cassandra"


def build_run_args(command: str, config: str, connectors: str) -> str:
    """The argument string after the executable.

    config / connectors are appended only when the caller did not already put
    them in `command`, so an explicit `--config` in --command wins.
    """
    args = command.strip()
    if "--config" not in args:
        args += f" --config {config}"
    if "--connectors" not in args:
        args += f" --connectors {connectors}"
    return args


# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
def systemd_path(name: str, user_mode: bool) -> Path:
    if user_mode:
        return Path.home() / ".config" / "systemd" / "user" / f"{name}.service"
    return SYSTEMD_SYSTEM_DIR / f"{name}.service"


def openrc_path(name: str) -> Path:
    return OPENRC_DIR / name


# --------------------------------------------------------------------------- #
# Renderers (pure)
# --------------------------------------------------------------------------- #
def render_systemd_unit(*, exec_cmd: str, description: str = "CassandraCTI aggregator",
                        env_file: Optional[str] = None, user_mode: bool = False) -> str:
    lines = [
        "# Generated by `cassandra service install`",
        "[Unit]",
        f"Description={description}",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=simple",
        f"ExecStart={exec_cmd}",
        "Restart=always",
        "RestartSec=10",
    ]
    if env_file:
        lines.append(f"EnvironmentFile={env_file}")
    lines += [
        "",
        "[Install]",
        f"WantedBy={'default.target' if user_mode else 'multi-user.target'}",
        "",
    ]
    return "\n".join(lines)


def render_openrc_script(*, exec_path: str, run_args_full: str,
                         description: str = "CassandraCTI aggregator",
                         name: str = "cassandra-cti") -> str:
    # supervise-daemon backgrounds the process and respawns it on crash
    # (respawn_max=0 = unlimited). Secrets go in /etc/conf.d/<name>, which
    # OpenRC sources automatically.
    return (
        "#!/sbin/openrc-run\n"
        "# Generated by `cassandra service install`\n\n"
        f'description="{description}"\n\n'
        f'command="{exec_path}"\n'
        f'command_args="{run_args_full}"\n'
        "command_background=true\n"
        'pidfile="/run/${RC_SVCNAME}.pid"\n'
        'output_log="/var/log/${RC_SVCNAME}.log"\n'
        'error_log="/var/log/${RC_SVCNAME}.log"\n\n'
        "supervisor=supervise-daemon\n"
        "respawn_delay=10\n"
        "respawn_max=0\n\n"
        "depend() {\n"
        "\tneed net\n"
        "\tafter net\n"
        "}\n"
    )


# --------------------------------------------------------------------------- #
# System actions
# --------------------------------------------------------------------------- #
def _run(cmd: List[str]) -> bool:
    try:
        return subprocess.run(cmd, check=False).returncode == 0  # nosec B603 -- fixed argv, no shell
    except (FileNotFoundError, OSError):
        return False


def enable_service(init: str, name: str, user_mode: bool) -> bool:
    if init == "systemd":
        sc = shutil.which("systemctl") or "systemctl"
        scope = ["--user"] if user_mode else []
        _run([sc, *scope, "daemon-reload"])
        return _run([sc, *scope, "enable", "--now", name])
    rcu = shutil.which("rc-update") or "rc-update"
    rcs = shutil.which("rc-service") or "rc-service"
    _run([rcu, "add", name, "default"])
    return _run([rcs, name, "start"])


def uninstall_service(init: str, name: str, user_mode: bool) -> Path:
    if init == "systemd":
        sc = shutil.which("systemctl") or "systemctl"
        scope = ["--user"] if user_mode else []
        _run([sc, *scope, "disable", "--now", name])
        _run([sc, *scope, "daemon-reload"])
        return systemd_path(name, user_mode)
    rcs = shutil.which("rc-service") or "rc-service"
    rcu = shutil.which("rc-update") or "rc-update"
    _run([rcs, name, "stop"])
    _run([rcu, "del", name, "default"])
    return openrc_path(name)


def status_service(init: str, name: str, user_mode: bool) -> bool:
    if init == "systemd":
        sc = shutil.which("systemctl") or "systemctl"
        scope = ["--user"] if user_mode else []
        return _run([sc, *scope, "status", name])
    rcs = shutil.which("rc-service") or "rc-service"
    return _run([rcs, name, "status"])


# --------------------------------------------------------------------------- #
# Human-facing hints (for --no-enable / degraded paths)
# --------------------------------------------------------------------------- #
def manual_enable_hint(init: str, name: str, user_mode: bool) -> str:
    if init == "systemd":
        u = " --user" if user_mode else ""
        return (f"  systemctl{u} daemon-reload\n"
                f"  systemctl{u} enable --now {name}")
    return (f"  rc-update add {name} default\n"
            f"  rc-service {name} start")


def status_hint(init: str, name: str, user_mode: bool) -> str:
    if init == "systemd":
        u = " --user" if user_mode else ""
        return f"Check it with:  systemctl{u} status {name}  (logs: journalctl{u} -u {name} -f)"
    return f"Check it with:  rc-service {name} status  (logs: /var/log/{name}.log)"
